// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIlAaHDqnetPtHjlUADNoWjvfCFlqX_WU',
    appId: '1:573732244427:web:91656e1bd21b30afe9c44e',
    messagingSenderId: '573732244427',
    projectId: 'kmart-2c7fd',
    authDomain: 'kmart-2c7fd.firebaseapp.com',
    storageBucket: 'kmart-2c7fd.appspot.com',
    measurementId: 'G-EKPL0KDW5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyKzX1n1p-igX8LZ0uQuUdU5gRxSNhfSY',
    appId: '1:573732244427:android:7eb8cca3fcf08128e9c44e',
    messagingSenderId: '573732244427',
    projectId: 'kmart-2c7fd',
    storageBucket: 'kmart-2c7fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNX2sE2gTbAdlvSC63DZvXfoHsVKH4VW8',
    appId: '1:573732244427:ios:e981484fe91f8fafe9c44e',
    messagingSenderId: '573732244427',
    projectId: 'kmart-2c7fd',
    storageBucket: 'kmart-2c7fd.appspot.com',
    androidClientId: '573732244427-du6oqqh5oqc2jcmath8tqgpehpui2m8v.apps.googleusercontent.com',
    iosClientId: '573732244427-mdgauqir8nl7ent31hu0htmgs1nijtj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.kmartAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNX2sE2gTbAdlvSC63DZvXfoHsVKH4VW8',
    appId: '1:573732244427:ios:e981484fe91f8fafe9c44e',
    messagingSenderId: '573732244427',
    projectId: 'kmart-2c7fd',
    storageBucket: 'kmart-2c7fd.appspot.com',
    androidClientId: '573732244427-du6oqqh5oqc2jcmath8tqgpehpui2m8v.apps.googleusercontent.com',
    iosClientId: '573732244427-mdgauqir8nl7ent31hu0htmgs1nijtj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.kmartAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIlAaHDqnetPtHjlUADNoWjvfCFlqX_WU',
    appId: '1:573732244427:web:6018e9c747cca76de9c44e',
    messagingSenderId: '573732244427',
    projectId: 'kmart-2c7fd',
    authDomain: 'kmart-2c7fd.firebaseapp.com',
    storageBucket: 'kmart-2c7fd.appspot.com',
    measurementId: 'G-BJSYYJF52Q',
  );
}
